networks:
  feynman-network:

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports: ["5432:5432"] # We expose this in dev for local development, mainly for the sqlx CLI
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - feynman-network
