/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * feynman-api
 * OpenAPI spec version: 0.1.0
 */
export interface CreateSessionPayload {
  topic: string;
}

export interface ErrorResponse {
  message: string;
}

export interface Message {
  content: string;
  created_at: string;
  id: number;
  role: string;
  session_id: string;
}

export type MessageRole = typeof MessageRole[keyof typeof MessageRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageRole = {
  User: 'User',
  Ai: 'Ai',
} as const;

export interface Session {
  created_at: string;
  id: string;
  status: string;
  topic: string;
  updated_at: string;
  user_id: string;
}

export type SessionStatus = typeof SessionStatus[keyof typeof SessionStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SessionStatus = {
  Active: 'Active',
  Ended: 'Ended',
} as const;

export interface UpdateSessionStatusPayload {
  status: SessionStatus;
}

